#version 460
#extension GL_EXT_ray_tracing : require

#include "layouts.glsl"

layout(set = RayTracingDescSet, binding = 0) uniform image2D uColorOutput;

layout(set = RayTracingDescSet, binding = 1) buffer _Reservoir {
};

layout(binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;
layout(binding = 1, set = 0, rgba32f) uniform image2D image;

void main() {
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(0.5, 0.5, 0.5, 1.0));
}